tasks:
  - before: |
      # installs nvm (Node Version Manager)
      curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.0/install.sh | bash

      # download and install Node.js (you may need to restart the terminal)
      nvm install 20

      # verifies the right Node.js version is in the environment
      node -v # should print `v20.17.0`

      # verifies the right npm version is in the environment
      npm -v # should print `10.8.2`

      sh -ci "$(curl -fsSL https://internetcomputer.org/install.sh)"

      dfx start --background --clean


vscode:
  extensions:
    - dfinity-foundation.vscode-motoko
    - ms-python.python

ports:
  - name: Replica
    port: 4943
    visibility: public
    onOpen: ignore
  - name: Dev Server
    port: 8080
    visibility: public
    onOpen: open-browser
